### ISSUE TITLE
支持IPv6的AAAA记录吗

### ISSUE THREAD

**Issue by LitingLin** [kaedei/aliyun-ddns-client-csharp#1]

**Comment by kaedei** [comment]
目前还不支持AAAA记录。
主要是不知道ipv6的外网地址怎么获得

**Comment by Nagico** [comment]
> 目前还不支持AAAA记录。
> 主要是不知道ipv6的外网地址怎么获得

ipv6的话能不能从ipconfig中抓取呢？

**Comment by LitingLin** [comment]
大部分情况下通过百度等方法查ip确实是够了。
主要是我之前网络拓扑比较复杂，比如多wan负载均衡、ipv6等，这种情况下通过ipconfig等查询网卡ip过滤出公网ip比较靠谱些。后来我自己写工具解决了，谢谢！

发自我的 iPhone

在 2019年2月10日，上午11:54，CoYangJR <notifications@github.com<mailto:notifications@github.com>> 写道：


目前还不支持AAAA记录。
主要是不知道ipv6的外网地址怎么获得

ipv6的话能不能从ipconfig中抓取呢？
