### ISSUE TITLE
希望更新能自主获取本机外网地址的功能就好了...

### ISSUE THREAD

**Issue by soevil** [kaedei/aliyun-ddns-client-csharp#14]
虽然依赖http://2018.ip138.com/ic.asp获取外网地址方便...但貌似这个地址会时不时的改变..这样某天就全部不行了...

**Comment by kaedei** [comment]
编译后的.exe.config文件里面可以修改这个网页地址，程序会去获取页面源码中出现的第一个IP。这样的服务网上还有很多可以用的

**Comment by kaedei** [comment]
自己建了个简单的[网站](https://whatsmyip.chinacloudsites.cn/)用来获取外网IP 
应该不会有依赖性问题了吧（大概）
