### ISSUE TITLE
I got issue

### ISSUE THREAD

**Issue by readpan** [kaedei/aliyun-ddns-client-csharp#4]
<Error><RequestId>554AEBFE-37EB-4F30-AC32-3B3470BF736A</RequestId><HostId>dns.aliyuncs.com</HostId><Code>IllegalTimestamp</Code><Message>The input parameter "Timestamp" that is mandatory for processing this request is not supplied.</Message></Error>

Hi,
     I got the error , can u help me . thx

**Comment by readpan** [comment]
I solved the error. The time of my system is not correct. :) But why it's about time?

**Comment by kaedei** [comment]
时间是用来计算签名（验证请求有效性）的参数之一，本地和服务器之间时间差异过大的话就会验证失败
